# direction: right

title: ARC Architecture {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: false
  }
}

# explanation: |md
#   # I can do headers

#   - lists
#   - lists

#   And other normal markdown stuff
# |

# positional controller linear.x angular.z
#

ttd: twist_to_diff

ds4: ds4_to_twist

pos_controller -> ttd: "/cmd_vel"

ds4 -> ttd: "/cmd_vel"

lw: left wheel {
  ac: accerelation_controller
  vesc: vesc_driver
  command_topic: |md
    /motor_left<br/>
    /motor<br/>
    /commands<br/>
    /speed<br/>
  |
  pos_topic: |md
    /motor_left<br/>
    /sensors<br/>
    /core<br/>
  |
}

lw.ac -- lw.command_topic -> lw.vesc
lw.vesc -- lw.pos_topic -> lw.ac: {
  style: {
    stroke: red
    stroke-dash: 5
  }
}

rw: right wheel {
  ac: acceleration_controller
  vesc: vesc_driver
  command_topic: |md
    /motor_left<br/>
    /motor<br/>
    /commands<br/>
    /speed<br/>
  |
  pos_topic: |md
    /motor_left<br/>
    /sensors<br/>
    /core<br/>
  |
}

rw.ac -- rw.command_topic -> rw.vesc
rw.vesc -- rw.pos_topic -> rw.ac: {
  style: {
    stroke: red
    stroke-dash: 5
  }
}

ttd -- command_topic_l -> lw.ac
ttd -- command_topic_r -> rw.ac
